/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
	-- To understand the distribution of the data accross catagories 
	   by grouping and joining the deimensions.
===============================================================================
*/

-- Find total customers by countries

SELECT
	country,
	COUNT(*)AS "total_customers" 
FROM gold.dim_customers
GROUP BY country
ORDER BY [total_customers] DESC

-- Find total customers by gender

SELECT
	gender,
	COUNT(*)AS "total_customers" 
FROM gold.dim_customers
GROUP BY gender
ORDER BY [total_customers] DESC

-- Find total products by catagory

SELECT 
	category,
	COUNT(*) AS total_products
FROM gold.dim_product
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each catagory

SELECT 
	category,
	AVG(cost) AS average_costs
FROM gold.dim_product
GROUP BY category
ORDER BY average_costs DESC

-- What is the Toatl revenue generated for each catagory

SELECT 
	category,
	SUM(sales_amount) AS total_revenue
FROM gold.fact_sales as s
LEFT JOIN gold.dim_product as p
	ON p.product_key = s.product_key
GROUP BY category
ORDER BY total_revenue DESC

-- Find total revenue is generated by each customer

SELECT 
	c.customer_id,
	c.first_name,
	c.last_name,
	SUM(sales_amount) AS total_revenue
FROM gold.fact_sales as s
LEFT JOIN gold.dim_customers as c
	ON c.customer_key = s.customer_key
GROUP BY 
	c.customer_id,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries

SELECT 
	country,
	SUM(quantity) AS total_sold_items
FROM gold.fact_sales as s
LEFT JOIN gold.dim_customers as c
	ON c.customer_key = s.customer_key
GROUP BY country
ORDER BY total_sold_items DESC